CREATE DATABASE IF NOT EXISTS publicacion CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci;

USE publicacion;

CREATE TABLE IF NOT EXISTS profesor
(dni				CHAR(9)			NOT NULL	PRIMARY KEY,
nombre				VARCHAR(50)		NOT NULL,
especialidad		VARCHAR(50)		NOT NULL);

CREATE TABLE IF NOT EXISTS publica
(dni				CHAR(9)			NOT NULL,
isbn				VARCHAR(13)		NOT NULL,
CONSTRAINT PRIMARY KEY (dni, isbn));

CREATE TABLE IF NOT EXISTS libro 
(isbn				CHAR(13)		NOT NULL	PRIMARY KEY,
fechPublicacion		DATE			NOT NULL,
titulo				VARCHAR(100)	NOT NULL,
numPaginas			INTEGER			NOT NULL,
editorial			VARCHAR(50)		NOT NULL,
formato				VARCHAR(50)		NOT NULL);

CREATE TABLE IF NOT EXISTS utiliza
(isbn				CHAR(13)		NOT NULL	PRIMARY KEY,
asignatura			VARCHAR(50)		NOT NULL);

CREATE TABLE IF NOT EXISTS asignatura
(nombre				VARCHAR(13)		NOT NULL	PRIMARY KEY);

ALTER TABLE publica ADD CONSTRAINT fk_pub_pro 
FOREIGN KEY (dni) REFERENCES profesor(dni)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE publica ADD CONSTRAINT fk_pub_lib 
FOREIGN KEY (isbn) REFERENCES libro(isbn)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE utiliza ADD CONSTRAINT fk_uti_lib 
FOREIGN KEY (isbn) REFERENCES libro(isbn)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE utiliza ADD CONSTRAINT fk_uti_asi 
FOREIGN KEY (asignatura) REFERENCES asignatura(nombre)
ON UPDATE CASCADE ON DELETE CASCADE;



